# Generated by Django 6.1.1 on 2026-09-10 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_statusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
